### ISSUE TITLE
Palettes and Effect won´t load up in domoticz

### ISSUE THREAD

**Issue by ProchyMicrochip** [frustreermeneer/domoticz-wled-plugin#13]
![image](https://user-images.githubusercontent.com/50979154/120305503-1919b280-c2d1-11eb-9d50-55c9e8c6d1f8.png)
Everything else works fine

**Comment by dbrb2** [comment]
The problem seems to be down to the scope of the JSONConn variable - which is a class variable but seems to be out of scope by the time is is used...

I have changed it to a global for now - which doesn't seem like the right solution, but does make things work :-)

**Comment by Creo2005** [comment]
> I have changed it to a global for now - which doesn't seem like the right solution, but does make things work :-)

How to do it??

**Comment by Creo2005** [comment]
After last update beta Domoticz to Version: 2021.1 (build 13746) all is OK
