### ISSUE TITLE
Palettes and Effect problem in domoticz

### ISSUE THREAD

**Issue by Creo2005** [frustreermeneer/domoticz-wled-plugin#14]
In log: Error: WLED: (WLED) Transport is not connected, write directive to 'JSONConn' ignored.
![Снимок экрана 2021-10-17 в 08 32 18](https://user-images.githubusercontent.com/10849149/137613250-08830baf-0aa3-42dc-a670-9d90a36dd527.png)

**Comment by Creo2005** [comment]
> In log: Error: WLED: (WLED) Transport is not connected, write directive to 'JSONConn' ignored. ![Снимок экрана 2021-10-17 в 08 32 18](https://user-images.githubusercontent.com/10849149/137613250-08830baf-0aa3-42dc-a670-9d90a36dd527.png)

After last update beta Domoticz to Version: 2021.1 (build 13746) all is OK

**Comment by qlinsky** [comment]
Hello, i have the same problem on latest domoticz stable version (2021.1). I tried update version to last beta (bulid 13788), but the problem still exists. 
![ledy-grafika](https://user-images.githubusercontent.com/77587834/139502963-47011797-a88f-44cc-9bd9-b3a1ac8054bf.jpg)
![ledy-grafika2](https://user-images.githubusercontent.com/77587834/139502968-a23181fe-efdb-4bad-91f7-3b2d3eab78b6.jpg)

**Comment by Creo2005** [comment]
May be help:
sudo chmod +x plugin.py
and restart domoticz

**Comment by qlinsky** [comment]
Thanks for the answer, but unfortunately it still doesn't work :/ Today I update beta version to 13801, but problem still exists

**Comment by Creo2005** [comment]
Try My  plugin.py
[plugin.py.zip](https://github.com/frustreermeneer/domoticz-wled-plugin/files/7446281/plugin.py.zip)
