### ISSUE TITLE
Plugin does not work, Domoticz stops working

### ISSUE THREAD

**Issue by sghazagh** [frustreermeneer/domoticz-wled-plugin#3]
Have added your plugin into my Domoticz 4.10717. It stops the http server and I cannot access the Domoticz web dashboard anymore unless I remove the plugin and restart it again.

Any advise?

**Comment by frustreermeneer** [comment]
Can you try updating Domoticz? 
Does your log have any errors?

**Comment by sghazagh** [comment]
Domoticz is already the latest version.
Nothing on log, as Domoticz crashes have no access to log web page
Not sure why not having log file in tmp folder though !!!

**Comment by frustreermeneer** [comment]
What are you running Domoticz on?
I'm using Raspbian 9 on a Raspberry Pi.

Have you tried logging to syslog? 
See: https://www.domoticz.com/wiki/Set_up_Domoticz_to_syslog

**Comment by sghazagh** [comment]
It's a device called Lemaker Guitar. ARM device similar to RPi.
No problem with device for sure.
OS is Ubuntu 16.04 LTS...

**Comment by George-Verboven** [comment]
You did a great Job.
Works perfect

Using Domoticz 4.10717 with Raspberry Pi 3B+ en WS2812B connected on Wemos D1 Mini

**Comment by jendrush** [comment]
I have probably exactly the same problem as @sghazagh. Everything done as instruction says(cloning, restarting domoticz, turning on notifications on wled etc.). Few seconds after WLED plugin Enabled in Domoticz, system stopps responding. Domoticz service have to be restarted, and WLED plugin Disabled to restore functionality. I've updated Python version, and when checking version with "sudo systemctl restart domoticz.service" it tells me: PluginSystem: Started, Python version '3.4.2'., so it should be fine.

**Comment by lukaszcholewka** [comment]
Also got the same problem. After installing and configure plugin Domoticz stop responding. For repair I should remove all plugin files and restart Domoticz. Cannot use this plugin on Raspberry and newest Domoticz

Edit: After Update domoticz and raspbian all works good.
