### ISSUE TITLE
ON/OFF FX Speed and FX Intensity doesn't work.

### ISSUE THREAD

**Issue by George-Verboven** [frustreermeneer/domoticz-wled-plugin#4]
**Hi Frustreermeneer,**
Great script, however ON/OFF FX Speed and FX Intensity doesn't work.
At least I see no difference/influence.
I assumed I can lock by example the adjusted speed or intensity by turning it off.

**Comment by frustreermeneer** [comment]
I will check if it still works.
Did you try to make the same settings in de WLED app or WLED website? 
Some effect speeds and intensities are not so obvious to see any difference.
