### ISSUE TITLE
Domoticz doesn't update on wled direct change

### ISSUE THREAD

**Issue by nunorios** [frustreermeneer/domoticz-wled-plugin#6]
Hello,

First, let me thank you about the plugin. Easy install and to use. All the commands from Domoticz to WLED work very well

However, I've a issue and it's related with the fact if I access wled lamp directly with the browser and change the status of the lamp, Domoticz doesn't get updated.

Is it something in the configuration?

Best regards and thanks for your time
Nuno

**Comment by frustreermeneer** [comment]
Hi, have you enabled UDP WLED broadcast under sync interfaces? With the right port?

**Comment by EvertJob** [comment]
Same issue. Sync is enabled by default as far I can see. On and off works fine but the status is Domoticz is always ‘On’

**Comment by salopette** [comment]
https://github.com/frustreermeneer/domoticz-wled-plugin/issues/7

**Comment by frustreermeneer** [comment]
This should be fixed with the latest version.
