### ISSUE TITLE
Color & Brightness On-Off  is not displayed correctly.

### ISSUE THREAD

**Issue by salopette** [frustreermeneer/domoticz-wled-plugin#7]
Hi, could you maybe fix this bug?

https://www.domoticz.com/forum/viewtopic.php?f=65&t=29669&start=40#p238375

**Comment by frustreermeneer** [comment]
> Hi. I have been told that the switch remains on even though the lamp has been switched off.
>Can you fix that?

How is the lamp switched off? By using the WLED app?

**Comment by salopette** [comment]
ower domoticz
