### ISSUE TITLE
Domoticz won't show WLED in the "Hardware" page.

### ISSUE THREAD

**Issue by bangelischan** [frustreermeneer/domoticz-wled-plugin#8]
I restarted the domoticz server few times with : "sudo systemctrl restart domoticz.service" and when the server is back on, I still dont have any sign of WLED.
I made sure to "Accept new hardware" and double check everything!

**Comment by frustreermeneer** [comment]
If you don't see WLED in the hardware page something has gone wrong installing the plugin.
Make sure you used the right paths (domoticz/plugins/wled).

**Comment by bangelischan** [comment]
Thank you hehe! I actually just found the problem! I tried running the plugin from command line, and i had «  no module Domoticz » installed, which  i then understood the python module failed to initialize in domoticz! Problem solved yahouu!

**Comment by antonlamers** [comment]
I reinstalled domoticz now I have an error by WLED. I did remove the directory WLED and reinstal WLED, but I don’t see WLED by the hardware. How must I remove WLED in domoticz
