### ISSUE TITLE
Segments support

### ISSUE THREAD

**Issue by Warsenius** [frustreermeneer/domoticz-wled-plugin#9]
Hi. awesome work. your plugin works as described. 
the only feature im missing is to work with the segments feature of wled.
If you could add this it would be amazing.

**Comment by wizardnl** [comment]
same here, thanks for the nice work also looking for a segment option for a special project hope you have some time for a new release. again thank you for the work so far

**Comment by frustreermeneer** [comment]
I'm not using segments myself yet. I have to get an idea on how to implement it in Domoticz. 
It would probably involve making controls per segment?
Any ideas?
